### ISSUE TITLE
Company register data - Performing arts companies

### ISSUE THREAD

**Issue by KDuerden** [drkane/find-that-charity-scrapers#9]
Arts companies are not necessarily going to be not for profit type but are likely to be funded by grantmakers. 
Can COH data be included based on Nature of business coding in addition to company type? 
If so, then I think there is a case for including companies with SIC code 90010 - Performing arts. 
There may be others under this classification that could be worth looking at too: http://www.siccodesupport.co.uk/sic-division.php?division=90

**Comment by drkane** [comment]
Good idea. Couple of options here:

 - we just add all companies. The disadvantages of this are the database gets a lot bigger, with many more potential mismatches for every search.
 - add discrete groups like you suggest. My only worry about this approach is that the SIC codes from Companies House are not always very good - so there's no guarantee that we'd pick up all arts ortganisations.

Another option is signposting to a separate resource for for-profit companies, like opencorporates.

**Comment by KDuerden** [comment]
I think we shouldn't add all companies, as it would dilute the effectiveness of the tool overall.

Regarding Arts orgs, the appendix in Arts Council's [Economic impact of the arts](https://www.artscouncil.org.uk/sites/default/files/download-file/Economic%20impact%20of%20arts%20and%20culture%20on%20the%20national%20economy%20FINAL_0_0.PDF) includes an appendix with the SIC that the research is based on, so that could be our guide for what to include, and just deal with the fact that some might get missed.

Good idea on signposting to OpenCorporates for companies not found.

**Comment by drkane** [comment]
Company filtering happens here: https://github.com/drkane/find-that-charity-scrapers/blob/master/findthatcharity_import/spiders/companies.py#L108-L109

**Comment by KDuerden** [comment]
How much work would it be to do a lookup/match of current GB-COH IDs of recipients against SIC codes, to find out if other industries could be worth including? The only other one that seems like it might feature is Human Health and Social Work Activities 86-88.

**Comment by drkane** [comment]
Here's the top 20 SIC codes I've matched from orgs with company numbers in grantnav

code  | name                                                                        | companies
------|-----------------------------------------------------------------------------|----------
88990 | Other social work activities without accommodation n.e.c.                   | 2879
86900 | Other human health activities                                               | 1836
85590 | Other education n.e.c.                                                      | 1817
94990 | Activities of other membership organizations n.e.c.                         | 1597
96090 | Other service activities n.e.c.                                             | 1268
82990 | Other business support service activities n.e.c.                            |  922
88100 | Social work activities without accommodation for the elderly and disabled   |  825
85600 | Educational support services                                                |  762
90030 | Artistic creation                                                           |  761
93199 | Other sports activities                                                     |  713
93120 | Activities of sport clubs                                                   |  691
90010 | Performing arts                                                             |  683
85310 | General secondary education                                                 |  655
93290 | Other amusement and recreation activities n.e.c.                            |  638
90040 | Operation of arts facilities                                                |  591
85200 | Primary education                                                           |  569
93110 | Operation of sports facilities                                              |  556
85520 | Cultural education                                                          |  534
63990 | Other information service activities n.e.c.                                 |  525
90020 | Support activities to performing arts                                       |  436

**Comment by KDuerden** [comment]
Amazing! Is it possible to break down by non-profit / for profit types? There may be some in that list where the overlap is almost total, and therefore not worth a separate filter?

**Comment by drkane** [comment]
Here's the same list for only for-profit types:

(NB the numbers are a lot smaller - only ~5% of recipients with company numbers are for-profit)

code  | name                                                              | companies
--|---|---
93120 | Activities of sport clubs                                         | 48
93110 | Operation of sports facilities                                    | 46
82990 | Other business support service activities n.e.c.                  | 44
43210 | Electrical installation                                           | 42
93199 | Other sports activities                                           | 38
70229 | Management consultancy activities other than financial management | 37
85590 | Other education n.e.c.                                            | 32
62090 | Other information technology service activities                   | 32
74909 | Other professional, scientific and technical activities n.e.c.    | 30
68209 | Other letting and operating of own or leased real estate          | 28
62012 | Business and domestic software development                        | 25
96090 | Other service activities n.e.c.                                   | 24
85600 | Educational support services                                      | 21
99999 | Dormant Company                                                   | 20
90030 | Artistic creation                                                 | 18
62020 | Information technology consultancy activities                     | 16
90010 | Performing arts                                                   | 15
88990 | Other social work activities without accommodation n.e.c.         | 15
86900 | Other human health activities                                     | 14
94990 | Activities of other membership organizations n.e.c.               | 13
